### Force redeploy ##### Just Merge
name: 'development pipeline'
on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  NODE_OPTIONS: "--max-old-space-size=8192"
jobs:
  ### test
  test:
    uses: Khalon-Bridge/composite-workflows/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
